# This is a configuration file for the bacon tool
#
# repository: https://github.com/Canop/bacon
# help: https://dystroy.org/bacon/config/
# example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "check"

[jobs.run]
command = [
    "cargo",
    "run",
    "--color",
    "always",
    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true
background = true

[jobs.test]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--",
    "--color",
    "always", # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true

[jobs.test-coverage]
command = [
    "cargo",
    "tarpaulin",
    "--skip-clean",
    "--color",
    "always",
]
need_stdout = true

[jobs.clippy]
command = [
    "cargo", 
    "clippy",
    "--all-targets",
    "--fix",
    "--allow-dirty",
    "--color", 
    "always",
]
need_stdout = false

[jobs.format]
command = [
    "cargo",
    "fmt",
]
need_stdout = true
allow_warnings = true
on_success = "job:test" # so it is clear it has finished

[jobs.update]
command = [
    "cargo",
    "update",
    "--color",
    "always"
]
need_stdout = false
on_success = "job:test" # so it is clear it has finished

[jobs.check]
command = [
    "cargo",
    "check",
    "--color",
    "always"
]
need_stdout = false

# Git jobs

[jobs.git-status]
command = [
    "git",
    "status",
]
need_stdout = true

[jobs.git-diff]
command = [
    "git",
    "diff",
]
need_stdout = true

[jobs.git-log]
command = [
    "git",
    "log",
    "--pretty=oneline",
]
need_stdout = true

[jobs.git-add]
command = [
    "git",
    "add",
    "--all"
]
need_stdout = true
on_success = "job:git-commit"

[jobs.git-commit]
command = [
    "git",
    "commit",
    "-m",
    "update",
]
need_stdout = true

[jobs.git-pull-rebase]
command = [
    "git",
    "pull",
    "--rebase",
]
need_stdout = true

[jobs.git-push]
command = [
    "git",
    "push",
]
need_stdout = true

[keybindings]
r = "job:run"
t = "job:test"
j = "job:test-coverage"
# c = "jobs:clippy"
f = "job:format"
u = "job:update"
s = "job:git-status"
d = "job:git-diff"
l = "job:git-log"
i = "job:git-add" # Runs: git add . && git commit
o = "job:git-pull-rebase"
p = "job:git-push"
# v = "jobs:check"